<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesMatoGrossoSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cidades')->insert([
        	['nome' => 'Acorizal', 'estado_id' => 11],
            ['nome' => 'Água Boa', 'estado_id' => 11],
            ['nome' => 'Alta Floresta', 'estado_id' => 11],
            ['nome' => 'Alto Araguaia', 'estado_id' => 11],
            ['nome' => 'Alto Boa Vista', 'estado_id' => 11],
            ['nome' => 'Alto Garças', 'estado_id' => 11],
            ['nome' => 'Alto Paraguai', 'estado_id' => 11],
            ['nome' => 'Alto Taquari', 'estado_id' => 11],
            ['nome' => 'Apiacás', 'estado_id' => 11],
            ['nome' => 'Araguaiana', 'estado_id' => 11],
            ['nome' => 'Araguainha', 'estado_id' => 11],
            ['nome' => 'Araputanga', 'estado_id' => 11],
            ['nome' => 'Arenápolis', 'estado_id' => 11],
            ['nome' => 'Aripuanã', 'estado_id' => 11],
            ['nome' => 'Barão de Melgaço', 'estado_id' => 11],
            ['nome' => 'Barra do Bugres', 'estado_id' => 11],
            ['nome' => 'Barra do Garças', 'estado_id' => 11],
            ['nome' => 'Bom Jesus do Araguaia', 'estado_id' => 11],
            ['nome' => 'Brasnorte', 'estado_id' => 11],
            ['nome' => 'Cáceres', 'estado_id' => 11],
            ['nome' => 'Campinápolis', 'estado_id' => 11],
            ['nome' => 'Campo Novo do Parecis', 'estado_id' => 11],
            ['nome' => 'Campo Verde', 'estado_id' => 11],
            ['nome' => 'Campos de Júlio', 'estado_id' => 11],
            ['nome' => 'Canabrava do Norte', 'estado_id' => 11],
            ['nome' => 'Canarana', 'estado_id' => 11],
            ['nome' => 'Carlinda', 'estado_id' => 11],
            ['nome' => 'Castanheira', 'estado_id' => 11],
            ['nome' => 'Chapada dos Guimarães', 'estado_id' => 11],
            ['nome' => 'Cláudia', 'estado_id' => 11],
            ['nome' => 'Cocalinho', 'estado_id' => 11],
            ['nome' => 'Colíder', 'estado_id' => 11],
            ['nome' => 'Colniza', 'estado_id' => 11],
            ['nome' => 'Comodoro', 'estado_id' => 11],
            ['nome' => 'Confresa', 'estado_id' => 11],
            ['nome' => 'Conquista d`Oeste', 'estado_id' => 11],
            ['nome' => 'Cotriguaçu', 'estado_id' => 11],
            ['nome' => 'Cuiabá', 'estado_id' => 11],
            ['nome' => 'Curvelândia', 'estado_id' => 11],
            ['nome' => 'Curvelândia', 'estado_id' => 11],
            ['nome' => 'Denise', 'estado_id' => 11],
            ['nome' => 'Diamantino', 'estado_id' => 11],
            ['nome' => 'Dom Aquino', 'estado_id' => 11],
            ['nome' => 'Feliz Natal', 'estado_id' => 11],
            ['nome' => 'Figueirópolis d`Oeste', 'estado_id' => 11],
            ['nome' => 'Gaúcha do Norte', 'estado_id' => 11],
            ['nome' => 'General Carneiro', 'estado_id' => 11],
            ['nome' => 'Glória d`Oeste', 'estado_id' => 11],
            ['nome' => 'Guarantã do Norte', 'estado_id' => 11],
            ['nome' => 'Guiratinga', 'estado_id' => 11],
            ['nome' => 'Indiavaí', 'estado_id' => 11],
            ['nome' => 'Ipiranga do Norte', 'estado_id' => 11],
            ['nome' => 'Itanhangá', 'estado_id' => 11],
            ['nome' => 'Itaúba', 'estado_id' => 11],
            ['nome' => 'Itiquira', 'estado_id' => 11],
            ['nome' => 'Jaciara', 'estado_id' => 11],
            ['nome' => 'Jangada', 'estado_id' => 11],
            ['nome' => 'Jauru', 'estado_id' => 11],
            ['nome' => 'Juara', 'estado_id' => 11],
            ['nome' => 'Juína', 'estado_id' => 11],
            ['nome' => 'Juruena', 'estado_id' => 11],
            ['nome' => 'Juscimeira', 'estado_id' => 11],
            ['nome' => 'Lambari d`Oeste', 'estado_id' => 11],
            ['nome' => 'Lucas do Rio Verde', 'estado_id' => 11],
            ['nome' => 'Luciára', 'estado_id' => 11],
            ['nome' => 'Marcelândia', 'estado_id' => 11],
            ['nome' => 'Matupá', 'estado_id' => 11],
            ['nome' => 'Mirassol d`Oeste', 'estado_id' => 11],
            ['nome' => 'Nobres', 'estado_id' => 11],
            ['nome' => 'Nortelândia', 'estado_id' => 11],
            ['nome' => 'Nossa Senhora do Livramento', 'estado_id' => 11],
            ['nome' => 'Nova Bandeirantes', 'estado_id' => 11],
            ['nome' => 'Nova Brasilândia', 'estado_id' => 11],
            ['nome' => 'Nova Canaã do Norte', 'estado_id' => 11],
            ['nome' => 'Nova Guarita', 'estado_id' => 11],
            ['nome' => 'Nova Lacerda', 'estado_id' => 11],
            ['nome' => 'Nova Marilândia', 'estado_id' => 11],
            ['nome' => 'Nova Maringá', 'estado_id' => 11],
            ['nome' => 'Nova Monte verde', 'estado_id' => 11],
            ['nome' => 'Nova Mutum', 'estado_id' => 11],
            ['nome' => 'Nova Olímpia', 'estado_id' => 11],
            ['nome' => 'Nova Santa Helena', 'estado_id' => 11],
            ['nome' => 'Nova Ubiratã', 'estado_id' => 11],
            ['nome' => 'Nova Xavantina', 'estado_id' => 11],
            ['nome' => 'Novo Horizonte do Norte', 'estado_id' => 11],
            ['nome' => 'Novo Mundo', 'estado_id' => 11],
            ['nome' => 'Novo Santo Antônio', 'estado_id' => 11],
            ['nome' => 'Novo São Joaquim', 'estado_id' => 11],
            ['nome' => 'Paranaíta', 'estado_id' => 11],
            ['nome' => 'Paranatinga', 'estado_id' => 11],
            ['nome' => 'Pedra Preta', 'estado_id' => 11],
            ['nome' => 'Peixoto de Azevedo', 'estado_id' => 11],
            ['nome' => 'Planalto da Serra', 'estado_id' => 11],
            ['nome' => 'Poconé', 'estado_id' => 11],
            ['nome' => 'Pontal do Araguaia', 'estado_id' => 11],
            ['nome' => 'Ponte Branca', 'estado_id' => 11],
            ['nome' => 'Pontes e Lacerda', 'estado_id' => 11],
            ['nome' => 'Porto Alegre do Norte', 'estado_id' => 11],
            ['nome' => 'Porto dos Gaúchos', 'estado_id' => 11],
            ['nome' => 'Porto Esperidião', 'estado_id' => 11],
            ['nome' => 'Porto Estrela', 'estado_id' => 11],
            ['nome' => 'Poxoréo', 'estado_id' => 11],
            ['nome' => 'Primavera do Leste', 'estado_id' => 11],
            ['nome' => 'Querência', 'estado_id' => 11],
            ['nome' => 'Reserva do Cabaçal', 'estado_id' => 11],
            ['nome' => 'Ribeirão Cascalheira', 'estado_id' => 11],
            ['nome' => 'Ribeirãozinho', 'estado_id' => 11],
            ['nome' => 'Rio Branco', 'estado_id' => 11],
            ['nome' => 'Rondolândia', 'estado_id' => 11],
            ['nome' => 'Rondonópolis', 'estado_id' => 11],
            ['nome' => 'Rosário Oeste', 'estado_id' => 11],
            ['nome' => 'Salto do Céu', 'estado_id' => 11],
            ['nome' => 'Santa Carmem', 'estado_id' => 11],
            ['nome' => 'Santa Cruz do Xingu', 'estado_id' => 11],
            ['nome' => 'Santa Rita do Trivelato', 'estado_id' => 11],
            ['nome' => 'Santa Terezinha', 'estado_id' => 11],
            ['nome' => 'Santo Afonso', 'estado_id' => 11],
            ['nome' => 'Santo Antônio do Leste', 'estado_id' => 11],
            ['nome' => 'Santo Antônio do Leverger', 'estado_id' => 11],
            ['nome' => 'São Félix do Araguaia', 'estado_id' => 11],
            ['nome' => 'São José do Povo', 'estado_id' => 11],
            ['nome' => 'São José do Rio Claro', 'estado_id' => 11],
            ['nome' => 'São José do Xingu', 'estado_id' => 11],
            ['nome' => 'São José dos Quatro Marcos', 'estado_id' => 11],
            ['nome' => 'São Pedro da Cipa', 'estado_id' => 11],
            ['nome' => 'Sapezal', 'estado_id' => 11],
            ['nome' => 'Serra Nova Dourada', 'estado_id' => 11],
            ['nome' => 'Sinop', 'estado_id' => 11],
            ['nome' => 'Sorriso', 'estado_id' => 11],
            ['nome' => 'Tabaporã', 'estado_id' => 11],
            ['nome' => 'Tangará da Serra', 'estado_id' => 11],
            ['nome' => 'Tapurah', 'estado_id' => 11],
            ['nome' => 'Terra Nova do Norte', 'estado_id' => 11],
            ['nome' => 'Tesouro', 'estado_id' => 11],
            ['nome' => 'Torixoréu', 'estado_id' => 11],
            ['nome' => 'União do Sul', 'estado_id' => 11],
            ['nome' => 'Vale de São Domingos', 'estado_id' => 11],
            ['nome' => 'Várzea Grande', 'estado_id' => 11],
            ['nome' => 'Vera', 'estado_id' => 11],
            ['nome' => 'Vila Bela da Santíssima Trindade', 'estado_id' => 11],
            ['nome' => 'Vila Rica', 'estado_id' => 11]
        ]);

        $this->command->info('Cidades do Mato Grosso importadas com sucesso!');
    }
}