<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesMinasGeraisSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cidades')->insert([
        	['nome' => 'Abadia dos Dourados', 'estado_id' => 13],
            ['nome' => 'Abaeté', 'estado_id' => 13],
            ['nome' => 'Abre Campo', 'estado_id' => 13],
            ['nome' => 'Acaiaca', 'estado_id' => 13],
            ['nome' => 'Açucena', 'estado_id' => 13],
            ['nome' => 'Água Boa', 'estado_id' => 13],
            ['nome' => 'Água Comprida', 'estado_id' => 13],
            ['nome' => 'Aguanil', 'estado_id' => 13],
            ['nome' => 'Águas Formosas', 'estado_id' => 13],
            ['nome' => 'Águas Vermelhas', 'estado_id' => 13],
            ['nome' => 'Aimorés', 'estado_id' => 13],
            ['nome' => 'Aiuruoca', 'estado_id' => 13],
            ['nome' => 'Alagoa', 'estado_id' => 13],
            ['nome' => 'Albertina', 'estado_id' => 13],
            ['nome' => 'Além Paraíba', 'estado_id' => 13],
            ['nome' => 'Alfenas', 'estado_id' => 13],
            ['nome' => 'Alfredo Vasconcelos', 'estado_id' => 13],
            ['nome' => 'Almenara', 'estado_id' => 13],
            ['nome' => 'Alpercata', 'estado_id' => 13],
            ['nome' => 'Alpinópolis', 'estado_id' => 13],
            ['nome' => 'Alterosa', 'estado_id' => 13],
            ['nome' => 'Alto Caparaó', 'estado_id' => 13],
            ['nome' => 'Alto Jequitibá', 'estado_id' => 13],
            ['nome' => 'Alto Rio Doce', 'estado_id' => 13],
            ['nome' => 'Alvarenga', 'estado_id' => 13],
            ['nome' => 'Alvinópolis', 'estado_id' => 13],
            ['nome' => 'Alvorada de Minas', 'estado_id' => 13],
            ['nome' => 'Amparo do Serra', 'estado_id' => 13],
            ['nome' => 'Andradas', 'estado_id' => 13],
            ['nome' => 'Andrelândia', 'estado_id' => 13],
            ['nome' => 'Angelândia', 'estado_id' => 13],
            ['nome' => 'Antônio Carlos', 'estado_id' => 13],
            ['nome' => 'Antônio Dias', 'estado_id' => 13],
            ['nome' => 'Antônio Prado de Minas', 'estado_id' => 13],
            ['nome' => 'Araçaí', 'estado_id' => 13],
            ['nome' => 'Aracitaba', 'estado_id' => 13],
            ['nome' => 'Araçuaí', 'estado_id' => 13],
            ['nome' => 'Araguari', 'estado_id' => 13],
            ['nome' => 'Arantina', 'estado_id' => 13],
            ['nome' => 'Araponga', 'estado_id' => 13],
            ['nome' => 'Araporã', 'estado_id' => 13],
            ['nome' => 'Arapuá', 'estado_id' => 13],
            ['nome' => 'Araújos', 'estado_id' => 13],
            ['nome' => 'Araxá', 'estado_id' => 13],
            ['nome' => 'Arceburgo', 'estado_id' => 13],
            ['nome' => 'Arcos', 'estado_id' => 13],
            ['nome' => 'Areado', 'estado_id' => 13],
            ['nome' => 'Argirita', 'estado_id' => 13],
            ['nome' => 'Aricanduva', 'estado_id' => 13],
            ['nome' => 'Arinos', 'estado_id' => 13],
            ['nome' => 'Astolfo Dutra', 'estado_id' => 13],
            ['nome' => 'Ataléia', 'estado_id' => 13],
            ['nome' => 'Augusto de Lima', 'estado_id' => 13],
            ['nome' => 'Baependi', 'estado_id' => 13],
            ['nome' => 'Baldim', 'estado_id' => 13],
            ['nome' => 'Bambuí', 'estado_id' => 13],
            ['nome' => 'Bandeira', 'estado_id' => 13],
            ['nome' => 'Bandeira do Sul', 'estado_id' => 13],
            ['nome' => 'Barão de Cocais', 'estado_id' => 13],
            ['nome' => 'Barão de Monte Alto', 'estado_id' => 13],
            ['nome' => 'Barbacena', 'estado_id' => 13],
            ['nome' => 'Barra Longa', 'estado_id' => 13],
            ['nome' => 'Barroso', 'estado_id' => 13],
            ['nome' => 'Bela Vista de Minas', 'estado_id' => 13],
            ['nome' => 'Belmiro Braga', 'estado_id' => 13],
            ['nome' => 'Belo Horizonte', 'estado_id' => 13],
            ['nome' => 'Belo Oriente', 'estado_id' => 13],
            ['nome' => 'Belo Vale', 'estado_id' => 13],
            ['nome' => 'Berilo', 'estado_id' => 13],
            ['nome' => 'Berizal', 'estado_id' => 13],
            ['nome' => 'Bertópolis', 'estado_id' => 13],
            ['nome' => 'Betim', 'estado_id' => 13],
            ['nome' => 'Bias Fortes', 'estado_id' => 13],
            ['nome' => 'Bicas', 'estado_id' => 13],
            ['nome' => 'Biquinhas', 'estado_id' => 13],
            ['nome' => 'Boa Esperança', 'estado_id' => 13],
            ['nome' => 'Bocaina de Minas', 'estado_id' => 13],
            ['nome' => 'Bocaiúva', 'estado_id' => 13],
            ['nome' => 'Bom Despacho', 'estado_id' => 13],
            ['nome' => 'Bom Jardim de Minas', 'estado_id' => 13],
            ['nome' => 'Bom Jesus da Penha', 'estado_id' => 13],
            ['nome' => 'Bom Jesus do Amparo', 'estado_id' => 13],
            ['nome' => 'Bom Jesus do Galho', 'estado_id' => 13],
            ['nome' => 'Bom Repouso', 'estado_id' => 13],
            ['nome' => 'Bom Sucesso', 'estado_id' => 13],
            ['nome' => 'Bonfim', 'estado_id' => 13],
            ['nome' => 'Bonfinópolis de Minas', 'estado_id' => 13],
            ['nome' => 'Bonito de Minas', 'estado_id' => 13],
            ['nome' => 'Borda da Mata', 'estado_id' => 13],
            ['nome' => 'Botelhos', 'estado_id' => 13],
            ['nome' => 'Botumirim', 'estado_id' => 13],
            ['nome' => 'Brás Pires', 'estado_id' => 13],
            ['nome' => 'Brasilândia de Minas', 'estado_id' => 13],
            ['nome' => 'Brasília de Minas', 'estado_id' => 13],
            ['nome' => 'Brasópolis', 'estado_id' => 13],
            ['nome' => 'Braúnas', 'estado_id' => 13],
            ['nome' => 'Brumadinho', 'estado_id' => 13],
            ['nome' => 'Bueno Brandão', 'estado_id' => 13],
            ['nome' => 'Buenópolis', 'estado_id' => 13],
            ['nome' => 'Bugre', 'estado_id' => 13],
            ['nome' => 'Buritis', 'estado_id' => 13],
            ['nome' => 'Buritizeiro', 'estado_id' => 13],
            ['nome' => 'Cabeceira Grande', 'estado_id' => 13],
            ['nome' => 'Cabo Verde', 'estado_id' => 13],
            ['nome' => 'Cachoeira da Prata', 'estado_id' => 13],
            ['nome' => 'Cachoeira de Minas', 'estado_id' => 13],
            ['nome' => 'Cachoeira de Pajeú', 'estado_id' => 13],
            ['nome' => 'Cachoeira Dourada', 'estado_id' => 13],
            ['nome' => 'Caetanópolis', 'estado_id' => 13],
            ['nome' => 'Caeté', 'estado_id' => 13],
            ['nome' => 'Caiana', 'estado_id' => 13],
            ['nome' => 'Cajuri', 'estado_id' => 13],
            ['nome' => 'Caldas', 'estado_id' => 13],
            ['nome' => 'Camacho', 'estado_id' => 13],
            ['nome' => 'Camanducaia', 'estado_id' => 13],
            ['nome' => 'Cambuí', 'estado_id' => 13],
            ['nome' => 'Cambuquira', 'estado_id' => 13],
            ['nome' => 'Campanário', 'estado_id' => 13],
            ['nome' => 'Campanha', 'estado_id' => 13],
            ['nome' => 'Campestre', 'estado_id' => 13],
            ['nome' => 'Campina Verde', 'estado_id' => 13],
            ['nome' => 'Campo Azul', 'estado_id' => 13],
            ['nome' => 'Campo Belo', 'estado_id' => 13],
            ['nome' => 'Campo do Meio', 'estado_id' => 13],
            ['nome' => 'Campo Florido', 'estado_id' => 13],
            ['nome' => 'Campos Altos', 'estado_id' => 13],
            ['nome' => 'Campos Gerais', 'estado_id' => 13],
            ['nome' => 'Cana Verde', 'estado_id' => 13],
            ['nome' => 'Canaã', 'estado_id' => 13],
            ['nome' => 'Canápolis', 'estado_id' => 13],
            ['nome' => 'Candeias', 'estado_id' => 13],
            ['nome' => 'Cantagalo', 'estado_id' => 13],
            ['nome' => 'Caparaó', 'estado_id' => 13],
            ['nome' => 'Capela Nova', 'estado_id' => 13],
            ['nome' => 'Capelinha', 'estado_id' => 13],
            ['nome' => 'Capetinga', 'estado_id' => 13],
            ['nome' => 'Capim Branco', 'estado_id' => 13],
            ['nome' => 'Capinópolis', 'estado_id' => 13],
            ['nome' => 'Capitão Andrade', 'estado_id' => 13],
            ['nome' => 'Capitão Enéas', 'estado_id' => 13],
            ['nome' => 'Capitólio', 'estado_id' => 13],
            ['nome' => 'Caputira', 'estado_id' => 13],
            ['nome' => 'Caraí', 'estado_id' => 13],
            ['nome' => 'Caranaíba', 'estado_id' => 13],
            ['nome' => 'Carandaí', 'estado_id' => 13],
            ['nome' => 'Carangola', 'estado_id' => 13],
            ['nome' => 'Caratinga', 'estado_id' => 13],
            ['nome' => 'Carbonita', 'estado_id' => 13],
            ['nome' => 'Careaçu', 'estado_id' => 13],
            ['nome' => 'Carlos Chagas', 'estado_id' => 13],
            ['nome' => 'Carmésia', 'estado_id' => 13],
            ['nome' => 'Carmo da Cachoeira', 'estado_id' => 13],
            ['nome' => 'Carmo da Mata', 'estado_id' => 13],
            ['nome' => 'Carmo de Minas', 'estado_id' => 13],
            ['nome' => 'Carmo do Cajuru', 'estado_id' => 13],
            ['nome' => 'Carmo do Paranaíba', 'estado_id' => 13],
            ['nome' => 'Carmo do Rio Claro', 'estado_id' => 13],
            ['nome' => 'Carmópolis de Minas', 'estado_id' => 13],
            ['nome' => 'Carneirinho', 'estado_id' => 13],
            ['nome' => 'Carrancas', 'estado_id' => 13],
            ['nome' => 'Carvalhópolis', 'estado_id' => 13],
            ['nome' => 'Carvalhos', 'estado_id' => 13],
            ['nome' => 'Casa Grande', 'estado_id' => 13],
            ['nome' => 'Cascalho Rico', 'estado_id' => 13],
            ['nome' => 'Cássia', 'estado_id' => 13],
            ['nome' => 'Cataguases', 'estado_id' => 13],
            ['nome' => 'Catas Altas', 'estado_id' => 13],
            ['nome' => 'Catas Altas da Noruega', 'estado_id' => 13],
            ['nome' => 'Catuji', 'estado_id' => 13],
            ['nome' => 'Catuti', 'estado_id' => 13],
            ['nome' => 'Caxambu', 'estado_id' => 13],
            ['nome' => 'Cedro do Abaeté', 'estado_id' => 13],
            ['nome' => 'Central de Minas', 'estado_id' => 13],
            ['nome' => 'Centralina', 'estado_id' => 13],
            ['nome' => 'Chácara', 'estado_id' => 13],
            ['nome' => 'Chalé', 'estado_id' => 13],
            ['nome' => 'Chapada do Norte', 'estado_id' => 13],
            ['nome' => 'Chapada Gaúcha', 'estado_id' => 13],
            ['nome' => 'Chiador', 'estado_id' => 13],
            ['nome' => 'Cipotânea', 'estado_id' => 13],
            ['nome' => 'Claraval', 'estado_id' => 13],
            ['nome' => 'Claro dos Poções', 'estado_id' => 13],
            ['nome' => 'Cláudio', 'estado_id' => 13],
            ['nome' => 'Coimbra', 'estado_id' => 13],
            ['nome' => 'Coluna', 'estado_id' => 13],
            ['nome' => 'Comendador Gomes', 'estado_id' => 13],
            ['nome' => 'Comercinho', 'estado_id' => 13],
            ['nome' => 'Conceição da Aparecida', 'estado_id' => 13],
            ['nome' => 'Conceição da Barra de Minas', 'estado_id' => 13],
            ['nome' => 'Conceição das Alagoas', 'estado_id' => 13],
            ['nome' => 'Conceição das Pedras', 'estado_id' => 13],
            ['nome' => 'Conceição de Ipanema', 'estado_id' => 13],
            ['nome' => 'Conceição do Mato Dentro', 'estado_id' => 13],
            ['nome' => 'Conceição do Pará', 'estado_id' => 13],
            ['nome' => 'Conceição do Rio Verde', 'estado_id' => 13],
            ['nome' => 'Conceição dos Ouros', 'estado_id' => 13],
            ['nome' => 'Cônego Marinho', 'estado_id' => 13],
            ['nome' => 'Confins', 'estado_id' => 13],
            ['nome' => 'Congonhal', 'estado_id' => 13],
            ['nome' => 'Congonhas', 'estado_id' => 13],
            ['nome' => 'Congonhas do Norte', 'estado_id' => 13],
            ['nome' => 'Conquista', 'estado_id' => 13],
            ['nome' => 'Conselheiro Lafaiete', 'estado_id' => 13],
            ['nome' => 'Conselheiro Pena', 'estado_id' => 13],
            ['nome' => 'Consolação', 'estado_id' => 13],
            ['nome' => 'Contagem', 'estado_id' => 13],
            ['nome' => 'Coqueiral', 'estado_id' => 13],
            ['nome' => 'Coração de Jesus', 'estado_id' => 13],
            ['nome' => 'Cordisburgo', 'estado_id' => 13],
            ['nome' => 'Cordislândia', 'estado_id' => 13],
            ['nome' => 'Corinto', 'estado_id' => 13],
            ['nome' => 'Coroaci', 'estado_id' => 13],
            ['nome' => 'Coromandel', 'estado_id' => 13],
            ['nome' => 'Coronel Fabriciano', 'estado_id' => 13],
            ['nome' => 'Coronel Murta', 'estado_id' => 13],
            ['nome' => 'Coronel Pacheco', 'estado_id' => 13],
            ['nome' => 'Coronel Xavier Chaves', 'estado_id' => 13],
            ['nome' => 'Córrego Danta', 'estado_id' => 13],
            ['nome' => 'Córrego do Bom Jesus', 'estado_id' => 13],
            ['nome' => 'Córrego Fundo', 'estado_id' => 13],
            ['nome' => 'Córrego Novo', 'estado_id' => 13],
            ['nome' => 'Couto de Magalhães de Minas', 'estado_id' => 13],
            ['nome' => 'Crisólita', 'estado_id' => 13],
            ['nome' => 'Cristais', 'estado_id' => 13],
            ['nome' => 'Cristália', 'estado_id' => 13],
            ['nome' => 'Cristiano Otoni', 'estado_id' => 13],
            ['nome' => 'Cristina', 'estado_id' => 13],
            ['nome' => 'Crucilândia', 'estado_id' => 13],
            ['nome' => 'Cruzeiro da Fortaleza', 'estado_id' => 13],
            ['nome' => 'Cruzília', 'estado_id' => 13],
            ['nome' => 'Cuparaque', 'estado_id' => 13],
            ['nome' => 'Curral de Dentro', 'estado_id' => 13],
            ['nome' => 'Curvelo', 'estado_id' => 13],
            ['nome' => 'Datas', 'estado_id' => 13],
            ['nome' => 'Delfim Moreira', 'estado_id' => 13],
            ['nome' => 'Delfinópolis', 'estado_id' => 13],
            ['nome' => 'Delta', 'estado_id' => 13],
            ['nome' => 'Descoberto', 'estado_id' => 13],
            ['nome' => 'Desterro de Entre Rios', 'estado_id' => 13],
            ['nome' => 'Desterro do Melo', 'estado_id' => 13],
            ['nome' => 'Diamantina', 'estado_id' => 13],
            ['nome' => 'Diogo de Vasconcelos', 'estado_id' => 13],
            ['nome' => 'Dionísio', 'estado_id' => 13],
            ['nome' => 'Divinésia', 'estado_id' => 13],
            ['nome' => 'Divino', 'estado_id' => 13],
            ['nome' => 'Divino das Laranjeiras', 'estado_id' => 13],
            ['nome' => 'Divinolândia de Minas', 'estado_id' => 13],
            ['nome' => 'Divinópolis', 'estado_id' => 13],
            ['nome' => 'Divisa Alegre', 'estado_id' => 13],
            ['nome' => 'Divisa Nova', 'estado_id' => 13],
            ['nome' => 'Divisópolis', 'estado_id' => 13],
            ['nome' => 'Dom Bosco', 'estado_id' => 13],
            ['nome' => 'Dom Cavati', 'estado_id' => 13],
            ['nome' => 'Dom Joaquim', 'estado_id' => 13],
            ['nome' => 'Dom Silvério', 'estado_id' => 13],
            ['nome' => 'Dom Viçoso', 'estado_id' => 13],
            ['nome' => 'Dona Eusébia', 'estado_id' => 13],
            ['nome' => 'Dores de Campos', 'estado_id' => 13],
            ['nome' => 'Dores de Guanhães', 'estado_id' => 13],
            ['nome' => 'Dores do Indaiá', 'estado_id' => 13],
            ['nome' => 'Dores do Turvo', 'estado_id' => 13],
            ['nome' => 'Doresópolis', 'estado_id' => 13],
            ['nome' => 'Douradoquara', 'estado_id' => 13],
            ['nome' => 'Durandé', 'estado_id' => 13],
            ['nome' => 'Elói Mendes', 'estado_id' => 13],
            ['nome' => 'Engenheiro Caldas', 'estado_id' => 13],
            ['nome' => 'Engenheiro Navarro', 'estado_id' => 13],
            ['nome' => 'Entre Folhas', 'estado_id' => 13],
            ['nome' => 'Entre Rios de Minas', 'estado_id' => 13],
            ['nome' => 'Ervália', 'estado_id' => 13],
            ['nome' => 'Esmeraldas', 'estado_id' => 13],
            ['nome' => 'Espera Feliz', 'estado_id' => 13],
            ['nome' => 'Espinosa', 'estado_id' => 13],
            ['nome' => 'Espírito Santo do Dourado', 'estado_id' => 13],
            ['nome' => 'Estiva', 'estado_id' => 13],
            ['nome' => 'Estrela Dalva', 'estado_id' => 13],
            ['nome' => 'Estrela do Indaiá', 'estado_id' => 13],
            ['nome' => 'Estrela do Sul', 'estado_id' => 13],
            ['nome' => 'Eugenópolis', 'estado_id' => 13],
            ['nome' => 'Ewbank da Câmara', 'estado_id' => 13],
            ['nome' => 'Extrema', 'estado_id' => 13],
            ['nome' => 'Fama', 'estado_id' => 13],
            ['nome' => 'Faria Lemos', 'estado_id' => 13],
            ['nome' => 'Felício dos Santos', 'estado_id' => 13],
            ['nome' => 'Felisburgo', 'estado_id' => 13],
            ['nome' => 'Felixlândia', 'estado_id' => 13],
            ['nome' => 'Fernandes Tourinho', 'estado_id' => 13],
            ['nome' => 'Ferros', 'estado_id' => 13],
            ['nome' => 'Fervedouro', 'estado_id' => 13],
            ['nome' => 'Florestal', 'estado_id' => 13],
            ['nome' => 'Formiga', 'estado_id' => 13],
            ['nome' => 'Formoso', 'estado_id' => 13],
            ['nome' => 'Fortaleza de Minas', 'estado_id' => 13],
            ['nome' => 'Fortuna de Minas', 'estado_id' => 13],
            ['nome' => 'Francisco Badaró', 'estado_id' => 13],
            ['nome' => 'Francisco Dumont', 'estado_id' => 13],
            ['nome' => 'Francisco Sá', 'estado_id' => 13],
            ['nome' => 'Franciscópolis', 'estado_id' => 13],
            ['nome' => 'Frei Gaspar', 'estado_id' => 13],
            ['nome' => 'Frei Inocêncio', 'estado_id' => 13],
            ['nome' => 'Frei Lagonegro', 'estado_id' => 13],
            ['nome' => 'Fronteira', 'estado_id' => 13],
            ['nome' => 'Fronteira dos Vales', 'estado_id' => 13],
            ['nome' => 'Fruta de Leite', 'estado_id' => 13],
            ['nome' => 'Frutal', 'estado_id' => 13],
            ['nome' => 'Funilândia', 'estado_id' => 13],
            ['nome' => 'Galiléia', 'estado_id' => 13],
            ['nome' => 'Gameleiras', 'estado_id' => 13],
            ['nome' => 'Glaucilândia', 'estado_id' => 13],
            ['nome' => 'Goiabeira', 'estado_id' => 13],
            ['nome' => 'Goianá', 'estado_id' => 13],
            ['nome' => 'Gonçalves', 'estado_id' => 13],
            ['nome' => 'Gonzaga', 'estado_id' => 13],
            ['nome' => 'Gouveia', 'estado_id' => 13],
            ['nome' => 'Governador Valadares', 'estado_id' => 13],
            ['nome' => 'Grão Mogol', 'estado_id' => 13],
            ['nome' => 'Grupiara', 'estado_id' => 13],
            ['nome' => 'Guanhães', 'estado_id' => 13],
            ['nome' => 'Guapé', 'estado_id' => 13],
            ['nome' => 'Guaraciaba', 'estado_id' => 13],
            ['nome' => 'Guaraciama', 'estado_id' => 13],
            ['nome' => 'Guaranésia', 'estado_id' => 13],
            ['nome' => 'Guarani', 'estado_id' => 13],
            ['nome' => 'Guarará', 'estado_id' => 13],
            ['nome' => 'Guarda-Mor', 'estado_id' => 13],
            ['nome' => 'Guaxupé', 'estado_id' => 13],
            ['nome' => 'Guidoval', 'estado_id' => 13],
            ['nome' => 'Guimarânia', 'estado_id' => 13],
            ['nome' => 'Guiricema', 'estado_id' => 13],
            ['nome' => 'Gurinhatã', 'estado_id' => 13],
            ['nome' => 'Heliodora', 'estado_id' => 13],
            ['nome' => 'Iapu', 'estado_id' => 13],
            ['nome' => 'Ibertioga', 'estado_id' => 13],
            ['nome' => 'Ibiá', 'estado_id' => 13],
            ['nome' => 'Ibiaí', 'estado_id' => 13],
            ['nome' => 'Ibiracatu', 'estado_id' => 13],
            ['nome' => 'Ibiraci', 'estado_id' => 13],
            ['nome' => 'Ibirité', 'estado_id' => 13],
            ['nome' => 'Ibitiúra de Minas', 'estado_id' => 13],
            ['nome' => 'Ibituruna', 'estado_id' => 13],
            ['nome' => 'Icaraí de Minas', 'estado_id' => 13],
            ['nome' => 'Igarapé', 'estado_id' => 13],
            ['nome' => 'Igaratinga', 'estado_id' => 13],
            ['nome' => 'Iguatama', 'estado_id' => 13],
            ['nome' => 'Ijaci', 'estado_id' => 13],
            ['nome' => 'Ilicínea', 'estado_id' => 13],
            ['nome' => 'Imbé de Minas', 'estado_id' => 13],
            ['nome' => 'Inconfidentes', 'estado_id' => 13],
            ['nome' => 'Indaiabira', 'estado_id' => 13],
            ['nome' => 'Indianópolis', 'estado_id' => 13],
            ['nome' => 'Ingaí', 'estado_id' => 13],
            ['nome' => 'Inhapim', 'estado_id' => 13],
            ['nome' => 'Inhaúma', 'estado_id' => 13],
            ['nome' => 'Inimutaba', 'estado_id' => 13],
            ['nome' => 'Ipaba', 'estado_id' => 13],
            ['nome' => 'Ipanema', 'estado_id' => 13],
            ['nome' => 'Ipatinga', 'estado_id' => 13],
            ['nome' => 'Ipiaçu', 'estado_id' => 13],
            ['nome' => 'Ipuiúna', 'estado_id' => 13],
            ['nome' => 'Iraí de Minas', 'estado_id' => 13],
            ['nome' => 'Itabira', 'estado_id' => 13],
            ['nome' => 'Itabirinha de Mantena', 'estado_id' => 13],
            ['nome' => 'Itabirito', 'estado_id' => 13],
            ['nome' => 'Itacambira', 'estado_id' => 13],
            ['nome' => 'Itacarambi', 'estado_id' => 13],
            ['nome' => 'Itaguara', 'estado_id' => 13],
            ['nome' => 'Itaipé', 'estado_id' => 13],
            ['nome' => 'Itajubá', 'estado_id' => 13],
            ['nome' => 'Itamarandiba', 'estado_id' => 13],
            ['nome' => 'Itamarati de Minas', 'estado_id' => 13],
            ['nome' => 'Itambacuri', 'estado_id' => 13],
            ['nome' => 'Itambé do Mato Dentro', 'estado_id' => 13],
            ['nome' => 'Itamogi', 'estado_id' => 13],
            ['nome' => 'Itamonte', 'estado_id' => 13],
            ['nome' => 'Itanhandu', 'estado_id' => 13],
            ['nome' => 'Itanhomi', 'estado_id' => 13],
            ['nome' => 'Itaobim', 'estado_id' => 13],
            ['nome' => 'Itapagipe', 'estado_id' => 13],
            ['nome' => 'Itapecerica', 'estado_id' => 13],
            ['nome' => 'Itapeva', 'estado_id' => 13],
            ['nome' => 'Itatiaiuçu', 'estado_id' => 13],
            ['nome' => 'Itaú de Minas', 'estado_id' => 13],
            ['nome' => 'Itaúna', 'estado_id' => 13],
            ['nome' => 'Itaverava', 'estado_id' => 13],
            ['nome' => 'Itinga', 'estado_id' => 13],
            ['nome' => 'Itueta', 'estado_id' => 13],
            ['nome' => 'Ituiutaba', 'estado_id' => 13],
            ['nome' => 'Itumirim', 'estado_id' => 13],
            ['nome' => 'Iturama', 'estado_id' => 13],
            ['nome' => 'Itutinga', 'estado_id' => 13],
            ['nome' => 'Jaboticatubas', 'estado_id' => 13],
            ['nome' => 'Jacinto', 'estado_id' => 13],
            ['nome' => 'Jacuí', 'estado_id' => 13],
            ['nome' => 'Jacutinga', 'estado_id' => 13],
            ['nome' => 'Jaguaraçu', 'estado_id' => 13],
            ['nome' => 'Jaíba', 'estado_id' => 13],
            ['nome' => 'Jampruca', 'estado_id' => 13],
            ['nome' => 'Janaúba', 'estado_id' => 13],
            ['nome' => 'Januária', 'estado_id' => 13],
            ['nome' => 'Japaraíba', 'estado_id' => 13],
            ['nome' => 'Japonvar', 'estado_id' => 13],
            ['nome' => 'Jeceaba', 'estado_id' => 13],
            ['nome' => 'Jenipapo de Minas', 'estado_id' => 13],
            ['nome' => 'Jequeri', 'estado_id' => 13],
            ['nome' => 'Jequitaí', 'estado_id' => 13],
            ['nome' => 'Jequitibá', 'estado_id' => 13],
            ['nome' => 'Jequitinhonha', 'estado_id' => 13],
            ['nome' => 'Jesuânia', 'estado_id' => 13],
            ['nome' => 'Joaíma', 'estado_id' => 13],
            ['nome' => 'Joanésia', 'estado_id' => 13],
            ['nome' => 'João Monlevade', 'estado_id' => 13],
            ['nome' => 'João Pinheiro', 'estado_id' => 13],
            ['nome' => 'Joaquim Felício', 'estado_id' => 13],
            ['nome' => 'Jordânia', 'estado_id' => 13],
            ['nome' => 'José Gonçalves de Minas', 'estado_id' => 13],
            ['nome' => 'José Raydan', 'estado_id' => 13],
            ['nome' => 'Josenópolis', 'estado_id' => 13],
            ['nome' => 'Juatuba', 'estado_id' => 13],
            ['nome' => 'Juiz de Fora', 'estado_id' => 13],
            ['nome' => 'Juramento', 'estado_id' => 13],
            ['nome' => 'Juruaia', 'estado_id' => 13],
            ['nome' => 'Juvenília', 'estado_id' => 13],
            ['nome' => 'Ladainha', 'estado_id' => 13],
            ['nome' => 'Lagamar', 'estado_id' => 13],
            ['nome' => 'Lagoa da Prata', 'estado_id' => 13],
            ['nome' => 'Lagoa dos Patos', 'estado_id' => 13],
            ['nome' => 'Lagoa Dourada', 'estado_id' => 13],
            ['nome' => 'Lagoa Formosa', 'estado_id' => 13],
            ['nome' => 'Lagoa Grande', 'estado_id' => 13],
            ['nome' => 'Lagoa Santa', 'estado_id' => 13],
            ['nome' => 'Lajinha', 'estado_id' => 13],
            ['nome' => 'Lambari', 'estado_id' => 13],
            ['nome' => 'Lamim', 'estado_id' => 13],
            ['nome' => 'Laranjal', 'estado_id' => 13],
            ['nome' => 'Lassance', 'estado_id' => 13],
            ['nome' => 'Lavras', 'estado_id' => 13],
            ['nome' => 'Leandro Ferreira', 'estado_id' => 13],
            ['nome' => 'Leme do Prado', 'estado_id' => 13],
            ['nome' => 'Leopoldina', 'estado_id' => 13],
            ['nome' => 'Liberdade', 'estado_id' => 13],
            ['nome' => 'Lima Duarte', 'estado_id' => 13],
            ['nome' => 'Limeira do Oeste', 'estado_id' => 13],
            ['nome' => 'Lontra', 'estado_id' => 13],
            ['nome' => 'Luisburgo', 'estado_id' => 13],
            ['nome' => 'Luislândia', 'estado_id' => 13],
            ['nome' => 'Luminárias', 'estado_id' => 13],
            ['nome' => 'Luz', 'estado_id' => 13],
            ['nome' => 'Machacalis', 'estado_id' => 13],
            ['nome' => 'Machado', 'estado_id' => 13],
            ['nome' => 'Madre de Deus de Minas', 'estado_id' => 13],
            ['nome' => 'Malacacheta', 'estado_id' => 13],
            ['nome' => 'Mamonas', 'estado_id' => 13],
            ['nome' => 'Manga', 'estado_id' => 13],
            ['nome' => 'Manhuaçu', 'estado_id' => 13],
            ['nome' => 'Manhumirim', 'estado_id' => 13],
            ['nome' => 'Mantena', 'estado_id' => 13],
            ['nome' => 'Mar de Espanha', 'estado_id' => 13],
            ['nome' => 'Maravilhas', 'estado_id' => 13],
            ['nome' => 'Maria da Fé', 'estado_id' => 13],
            ['nome' => 'Mariana', 'estado_id' => 13],
            ['nome' => 'Marilac', 'estado_id' => 13],
            ['nome' => 'Mário Campos', 'estado_id' => 13],
            ['nome' => 'Maripá de Minas', 'estado_id' => 13],
            ['nome' => 'Marliéria', 'estado_id' => 13],
            ['nome' => 'Marmelópolis', 'estado_id' => 13],
            ['nome' => 'Martinho Campos', 'estado_id' => 13],
            ['nome' => 'Martins Soares', 'estado_id' => 13],
            ['nome' => 'Mata Verde', 'estado_id' => 13],
            ['nome' => 'Materlândia', 'estado_id' => 13],
            ['nome' => 'Mateus Leme', 'estado_id' => 13],
            ['nome' => 'Mathias Lobato', 'estado_id' => 13],
            ['nome' => 'Matias Barbosa', 'estado_id' => 13],
            ['nome' => 'Matias Cardoso', 'estado_id' => 13],
            ['nome' => 'Matipó', 'estado_id' => 13],
            ['nome' => 'Mato Verde', 'estado_id' => 13],
            ['nome' => 'Matozinhos', 'estado_id' => 13],
            ['nome' => 'Matutina', 'estado_id' => 13],
            ['nome' => 'Medeiros', 'estado_id' => 13],
            ['nome' => 'Medina', 'estado_id' => 13],
            ['nome' => 'Mendes Pimentel', 'estado_id' => 13],
            ['nome' => 'Mercês', 'estado_id' => 13],
            ['nome' => 'Mesquita', 'estado_id' => 13],
            ['nome' => 'Minas Novas', 'estado_id' => 13],
            ['nome' => 'Minduri', 'estado_id' => 13],
            ['nome' => 'Mirabela', 'estado_id' => 13],
            ['nome' => 'Miradouro', 'estado_id' => 13],
            ['nome' => 'Miraí', 'estado_id' => 13],
            ['nome' => 'Miravânia', 'estado_id' => 13],
            ['nome' => 'Moeda', 'estado_id' => 13],
            ['nome' => 'Moema', 'estado_id' => 13],
            ['nome' => 'Monjolos', 'estado_id' => 13],
            ['nome' => 'Monsenhor Paulo', 'estado_id' => 13],
            ['nome' => 'Montalvânia', 'estado_id' => 13],
            ['nome' => 'Monte Alegre de Minas', 'estado_id' => 13],
            ['nome' => 'Monte Azul', 'estado_id' => 13],
            ['nome' => 'Monte Belo', 'estado_id' => 13],
            ['nome' => 'Monte Carmelo', 'estado_id' => 13],
            ['nome' => 'Monte Formoso', 'estado_id' => 13],
            ['nome' => 'Monte Santo de Minas', 'estado_id' => 13],
            ['nome' => 'Monte Sião', 'estado_id' => 13]            
        ]);

        DB::table('cidades')->insert([
            ['nome' => 'Montes Claros', 'estado_id' => 13],
            ['nome' => 'Montezuma', 'estado_id' => 13],
            ['nome' => 'Morada Nova de Minas', 'estado_id' => 13],
            ['nome' => 'Morro da Garça', 'estado_id' => 13],
            ['nome' => 'Morro do Pilar', 'estado_id' => 13],
            ['nome' => 'Munhoz', 'estado_id' => 13],
            ['nome' => 'Muriaé', 'estado_id' => 13],
            ['nome' => 'Mutum', 'estado_id' => 13],
            ['nome' => 'Muzambinho', 'estado_id' => 13],
            ['nome' => 'Nacip Raydan', 'estado_id' => 13],
            ['nome' => 'Nanuque', 'estado_id' => 13],
            ['nome' => 'Naque', 'estado_id' => 13],
            ['nome' => 'Natalândia', 'estado_id' => 13],
            ['nome' => 'Natércia', 'estado_id' => 13],
            ['nome' => 'Nazareno', 'estado_id' => 13],
            ['nome' => 'Nepomuceno', 'estado_id' => 13],
            ['nome' => 'Ninheira', 'estado_id' => 13],
            ['nome' => 'Nova Belém', 'estado_id' => 13],
            ['nome' => 'Nova Era', 'estado_id' => 13],
            ['nome' => 'Nova Lima', 'estado_id' => 13],
            ['nome' => 'Nova Módica', 'estado_id' => 13],
            ['nome' => 'Nova Ponte', 'estado_id' => 13],
            ['nome' => 'Nova Porteirinha', 'estado_id' => 13],
            ['nome' => 'Nova Resende', 'estado_id' => 13],
            ['nome' => 'Nova Serrana', 'estado_id' => 13],
            ['nome' => 'Nova União', 'estado_id' => 13],
            ['nome' => 'Novo Cruzeiro', 'estado_id' => 13],
            ['nome' => 'Novo Oriente de Minas', 'estado_id' => 13],
            ['nome' => 'Novorizonte', 'estado_id' => 13],
            ['nome' => 'Olaria', 'estado_id' => 13],
            ['nome' => 'Olhos-d`Água', 'estado_id' => 13],
            ['nome' => 'Olímpio Noronha', 'estado_id' => 13],
            ['nome' => 'Oliveira', 'estado_id' => 13],
            ['nome' => 'Oliveira Fortes', 'estado_id' => 13],
            ['nome' => 'Onça de Pitangui', 'estado_id' => 13],
            ['nome' => 'Oratórios', 'estado_id' => 13],
            ['nome' => 'Orizânia', 'estado_id' => 13],
            ['nome' => 'Ouro Branco', 'estado_id' => 13],
            ['nome' => 'Ouro Fino', 'estado_id' => 13],
            ['nome' => 'Ouro Preto', 'estado_id' => 13],
            ['nome' => 'Ouro Verde de Minas', 'estado_id' => 13],
            ['nome' => 'Padre Carvalho', 'estado_id' => 13],
            ['nome' => 'Padre Paraíso', 'estado_id' => 13],
            ['nome' => 'Pai Pedro', 'estado_id' => 13],
            ['nome' => 'Paineiras', 'estado_id' => 13],
            ['nome' => 'Pains', 'estado_id' => 13],
            ['nome' => 'Paiva', 'estado_id' => 13],
            ['nome' => 'Palma', 'estado_id' => 13],
            ['nome' => 'Palmópolis', 'estado_id' => 13],
            ['nome' => 'Papagaios', 'estado_id' => 13],
            ['nome' => 'Pará de Minas', 'estado_id' => 13],
            ['nome' => 'Paracatu', 'estado_id' => 13],
            ['nome' => 'Paraguaçu', 'estado_id' => 13],
            ['nome' => 'Paraisópolis', 'estado_id' => 13],
            ['nome' => 'Paraopeba', 'estado_id' => 13],
            ['nome' => 'Passa Quatro', 'estado_id' => 13],
            ['nome' => 'Passa Tempo', 'estado_id' => 13],
            ['nome' => 'Passabém', 'estado_id' => 13],
            ['nome' => 'Passa-Vinte', 'estado_id' => 13],
            ['nome' => 'Passos', 'estado_id' => 13],
            ['nome' => 'Patis', 'estado_id' => 13],
            ['nome' => 'Patos de Minas', 'estado_id' => 13],
            ['nome' => 'Patrocínio', 'estado_id' => 13],
            ['nome' => 'Patrocínio do Muriaé', 'estado_id' => 13],
            ['nome' => 'Paula Cândido', 'estado_id' => 13],
            ['nome' => 'Paulistas', 'estado_id' => 13],
            ['nome' => 'Pavão', 'estado_id' => 13],
            ['nome' => 'Peçanha', 'estado_id' => 13],
            ['nome' => 'Pedra Azul', 'estado_id' => 13],
            ['nome' => 'Pedra Bonita', 'estado_id' => 13],
            ['nome' => 'Pedra do Anta', 'estado_id' => 13],
            ['nome' => 'Pedra do Indaiá', 'estado_id' => 13],
            ['nome' => 'Pedra Dourada', 'estado_id' => 13],
            ['nome' => 'Pedralva', 'estado_id' => 13],
            ['nome' => 'Pedras de Maria da Cruz', 'estado_id' => 13],
            ['nome' => 'Pedrinópolis', 'estado_id' => 13],
            ['nome' => 'Pedro Leopoldo', 'estado_id' => 13],
            ['nome' => 'Pedro Teixeira', 'estado_id' => 13],
            ['nome' => 'Pequeri', 'estado_id' => 13],
            ['nome' => 'Pequi', 'estado_id' => 13],
            ['nome' => 'Perdigão', 'estado_id' => 13],
            ['nome' => 'Perdizes', 'estado_id' => 13],
            ['nome' => 'Perdões', 'estado_id' => 13],
            ['nome' => 'Periquito', 'estado_id' => 13],
            ['nome' => 'Pescador', 'estado_id' => 13],
            ['nome' => 'Piau', 'estado_id' => 13],
            ['nome' => 'Piedade de Caratinga', 'estado_id' => 13],
            ['nome' => 'Piedade de Ponte Nova', 'estado_id' => 13],
            ['nome' => 'Piedade do Rio Grande', 'estado_id' => 13],
            ['nome' => 'Piedade dos Gerais', 'estado_id' => 13],
            ['nome' => 'Pimenta', 'estado_id' => 13],
            ['nome' => 'Pingo-d`Água', 'estado_id' => 13],
            ['nome' => 'Pintópolis', 'estado_id' => 13],
            ['nome' => 'Piracema', 'estado_id' => 13],
            ['nome' => 'Pirajuba', 'estado_id' => 13],
            ['nome' => 'Piranga', 'estado_id' => 13],
            ['nome' => 'Piranguçu', 'estado_id' => 13],
            ['nome' => 'Piranguinho', 'estado_id' => 13],
            ['nome' => 'Pirapetinga', 'estado_id' => 13],
            ['nome' => 'Pirapora', 'estado_id' => 13],
            ['nome' => 'Piraúba', 'estado_id' => 13],
            ['nome' => 'Pitangui', 'estado_id' => 13],
            ['nome' => 'Piumhi', 'estado_id' => 13],
            ['nome' => 'Planura', 'estado_id' => 13],
            ['nome' => 'Poço Fundo', 'estado_id' => 13],
            ['nome' => 'Poços de Caldas', 'estado_id' => 13],
            ['nome' => 'Pocrane', 'estado_id' => 13],
            ['nome' => 'Pompéu', 'estado_id' => 13],
            ['nome' => 'Ponte Nova', 'estado_id' => 13],
            ['nome' => 'Ponto Chique', 'estado_id' => 13],
            ['nome' => 'Ponto dos Volantes', 'estado_id' => 13],
            ['nome' => 'Porteirinha', 'estado_id' => 13],
            ['nome' => 'Porto Firme', 'estado_id' => 13],
            ['nome' => 'Poté', 'estado_id' => 13],
            ['nome' => 'Pouso Alegre', 'estado_id' => 13],
            ['nome' => 'Pouso Alto', 'estado_id' => 13],
            ['nome' => 'Prados', 'estado_id' => 13],
            ['nome' => 'Prata', 'estado_id' => 13],
            ['nome' => 'Pratápolis', 'estado_id' => 13],
            ['nome' => 'Pratinha', 'estado_id' => 13],
            ['nome' => 'Presidente Bernardes', 'estado_id' => 13],
            ['nome' => 'Presidente Juscelino', 'estado_id' => 13],
            ['nome' => 'Presidente Kubitschek', 'estado_id' => 13],
            ['nome' => 'Presidente Olegário', 'estado_id' => 13],
            ['nome' => 'Prudente de Morais', 'estado_id' => 13],
            ['nome' => 'Quartel Geral', 'estado_id' => 13],
            ['nome' => 'Queluzito', 'estado_id' => 13],
            ['nome' => 'Raposos', 'estado_id' => 13],
            ['nome' => 'Raul Soares', 'estado_id' => 13],
            ['nome' => 'Recreio', 'estado_id' => 13],
            ['nome' => 'Reduto', 'estado_id' => 13],
            ['nome' => 'Resende Costa', 'estado_id' => 13],
            ['nome' => 'Resplendor', 'estado_id' => 13],
            ['nome' => 'Ressaquinha', 'estado_id' => 13],
            ['nome' => 'Riachinho', 'estado_id' => 13],
            ['nome' => 'Riacho dos Machados', 'estado_id' => 13],
            ['nome' => 'Ribeirão das Neves', 'estado_id' => 13],
            ['nome' => 'Ribeirão Vermelho', 'estado_id' => 13],
            ['nome' => 'Rio Acima', 'estado_id' => 13],
            ['nome' => 'Rio Casca', 'estado_id' => 13],
            ['nome' => 'Rio do Prado', 'estado_id' => 13],
            ['nome' => 'Rio Doce', 'estado_id' => 13],
            ['nome' => 'Rio Espera', 'estado_id' => 13],
            ['nome' => 'Rio Manso', 'estado_id' => 13],
            ['nome' => 'Rio Novo', 'estado_id' => 13],
            ['nome' => 'Rio Paranaíba', 'estado_id' => 13],
            ['nome' => 'Rio Pardo de Minas', 'estado_id' => 13],
            ['nome' => 'Rio Piracicaba', 'estado_id' => 13],
            ['nome' => 'Rio Pomba', 'estado_id' => 13],
            ['nome' => 'Rio Preto', 'estado_id' => 13],
            ['nome' => 'Rio Vermelho', 'estado_id' => 13],
            ['nome' => 'Ritápolis', 'estado_id' => 13],
            ['nome' => 'Rochedo de Minas', 'estado_id' => 13],
            ['nome' => 'Rodeiro', 'estado_id' => 13],
            ['nome' => 'Romaria', 'estado_id' => 13],
            ['nome' => 'Rosário da Limeira', 'estado_id' => 13],
            ['nome' => 'Rubelita', 'estado_id' => 13],
            ['nome' => 'Rubim', 'estado_id' => 13],
            ['nome' => 'Sabará', 'estado_id' => 13],
            ['nome' => 'Sabinópolis', 'estado_id' => 13],
            ['nome' => 'Sacramento', 'estado_id' => 13],
            ['nome' => 'Salinas', 'estado_id' => 13],
            ['nome' => 'Salto da Divisa', 'estado_id' => 13],
            ['nome' => 'Santa Bárbara', 'estado_id' => 13],
            ['nome' => 'Santa Bárbara do Leste', 'estado_id' => 13],
            ['nome' => 'Santa Bárbara do Monte Verde', 'estado_id' => 13],
            ['nome' => 'Santa Bárbara do Tugúrio', 'estado_id' => 13],
            ['nome' => 'Santa Cruz de Minas', 'estado_id' => 13],
            ['nome' => 'Santa Cruz de Salinas', 'estado_id' => 13],
            ['nome' => 'Santa Cruz do Escalvado', 'estado_id' => 13],
            ['nome' => 'Santa Efigênia de Minas', 'estado_id' => 13],
            ['nome' => 'Santa Fé de Minas', 'estado_id' => 13],
            ['nome' => 'Santa Helena de Minas', 'estado_id' => 13],
            ['nome' => 'Santa Juliana', 'estado_id' => 13],
            ['nome' => 'Santa Luzia', 'estado_id' => 13],
            ['nome' => 'Santa Margarida', 'estado_id' => 13],
            ['nome' => 'Santa Maria de Itabira', 'estado_id' => 13],
            ['nome' => 'Santa Maria do Salto', 'estado_id' => 13],
            ['nome' => 'Santa Maria do Suaçuí', 'estado_id' => 13],
            ['nome' => 'Santa Rita de Caldas', 'estado_id' => 13],
            ['nome' => 'Santa Rita de Ibitipoca', 'estado_id' => 13],
            ['nome' => 'Santa Rita de Jacutinga', 'estado_id' => 13],
            ['nome' => 'Santa Rita de Minas', 'estado_id' => 13],
            ['nome' => 'Santa Rita do Itueto', 'estado_id' => 13],
            ['nome' => 'Santa Rita do Sapucaí', 'estado_id' => 13],
            ['nome' => 'Santa Rosa da Serra', 'estado_id' => 13],
            ['nome' => 'Santa Vitória', 'estado_id' => 13],
            ['nome' => 'Santana da Vargem', 'estado_id' => 13],
            ['nome' => 'Santana de Cataguases', 'estado_id' => 13],
            ['nome' => 'Santana de Pirapama', 'estado_id' => 13],
            ['nome' => 'Santana do Deserto', 'estado_id' => 13],
            ['nome' => 'Santana do Garambéu', 'estado_id' => 13],
            ['nome' => 'Santana do Jacaré', 'estado_id' => 13],
            ['nome' => 'Santana do Manhuaçu', 'estado_id' => 13],
            ['nome' => 'Santana do Paraíso', 'estado_id' => 13],
            ['nome' => 'Santana do Riacho', 'estado_id' => 13],
            ['nome' => 'Santana dos Montes', 'estado_id' => 13],
            ['nome' => 'Santo Antônio do Amparo', 'estado_id' => 13],
            ['nome' => 'Santo Antônio do Aventureiro', 'estado_id' => 13],
            ['nome' => 'Santo Antônio do Grama', 'estado_id' => 13],
            ['nome' => 'Santo Antônio do Itambé', 'estado_id' => 13],
            ['nome' => 'Santo Antônio do Jacinto', 'estado_id' => 13],
            ['nome' => 'Santo Antônio do Monte', 'estado_id' => 13],
            ['nome' => 'Santo Antônio do Retiro', 'estado_id' => 13],
            ['nome' => 'Santo Antônio do Rio Abaixo', 'estado_id' => 13],
            ['nome' => 'Santo Hipólito', 'estado_id' => 13],
            ['nome' => 'Santos Dumont', 'estado_id' => 13],
            ['nome' => 'São Bento Abade', 'estado_id' => 13],
            ['nome' => 'São Brás do Suaçuí', 'estado_id' => 13],
            ['nome' => 'São Domingos das Dores', 'estado_id' => 13],
            ['nome' => 'São Domingos do Prata', 'estado_id' => 13],
            ['nome' => 'São Félix de Minas', 'estado_id' => 13],
            ['nome' => 'São Francisco', 'estado_id' => 13],
            ['nome' => 'São Francisco de Paula', 'estado_id' => 13],
            ['nome' => 'São Francisco de Sales', 'estado_id' => 13],
            ['nome' => 'São Francisco do Glória', 'estado_id' => 13],
            ['nome' => 'São Geraldo', 'estado_id' => 13],
            ['nome' => 'São Geraldo da Piedade', 'estado_id' => 13],
            ['nome' => 'São Geraldo do Baixio', 'estado_id' => 13],
            ['nome' => 'São Gonçalo do Abaeté', 'estado_id' => 13],
            ['nome' => 'São Gonçalo do Pará', 'estado_id' => 13],
            ['nome' => 'São Gonçalo do Rio Abaixo', 'estado_id' => 13],
            ['nome' => 'São Gonçalo do Rio Preto', 'estado_id' => 13],
            ['nome' => 'São Gonçalo do Sapucaí', 'estado_id' => 13],
            ['nome' => 'São Gotardo', 'estado_id' => 13],
            ['nome' => 'São João Batista do Glória', 'estado_id' => 13],
            ['nome' => 'São João da Lagoa', 'estado_id' => 13],
            ['nome' => 'São João da Mata', 'estado_id' => 13],
            ['nome' => 'São João da Ponte', 'estado_id' => 13],
            ['nome' => 'São João das Missões', 'estado_id' => 13],
            ['nome' => 'São João del Rei', 'estado_id' => 13],
            ['nome' => 'São João do Manhuaçu', 'estado_id' => 13],
            ['nome' => 'São João do Manteninha', 'estado_id' => 13],
            ['nome' => 'São João do Oriente', 'estado_id' => 13],
            ['nome' => 'São João do Pacuí', 'estado_id' => 13],
            ['nome' => 'São João do Paraíso', 'estado_id' => 13],
            ['nome' => 'São João Evangelista', 'estado_id' => 13],
            ['nome' => 'São João Nepomuceno', 'estado_id' => 13],
            ['nome' => 'São Joaquim de Bicas', 'estado_id' => 13],
            ['nome' => 'São José da Barra', 'estado_id' => 13],
            ['nome' => 'São José da Lapa', 'estado_id' => 13],
            ['nome' => 'São José da Safira', 'estado_id' => 13],
            ['nome' => 'São José da Varginha', 'estado_id' => 13],
            ['nome' => 'São José do Alegre', 'estado_id' => 13],
            ['nome' => 'São José do Divino', 'estado_id' => 13],
            ['nome' => 'São José do Goiabal', 'estado_id' => 13],
            ['nome' => 'São José do Jacuri', 'estado_id' => 13],
            ['nome' => 'São José do Mantimento', 'estado_id' => 13],
            ['nome' => 'São Lourenço', 'estado_id' => 13],
            ['nome' => 'São Miguel do Anta', 'estado_id' => 13],
            ['nome' => 'São Pedro da União', 'estado_id' => 13],
            ['nome' => 'São Pedro do Suaçuí', 'estado_id' => 13],
            ['nome' => 'São Pedro dos Ferros', 'estado_id' => 13],
            ['nome' => 'São Romão', 'estado_id' => 13],
            ['nome' => 'São Roque de Minas', 'estado_id' => 13],
            ['nome' => 'São Sebastião da Bela Vista', 'estado_id' => 13],
            ['nome' => 'São Sebastião da Vargem Alegre', 'estado_id' => 13],
            ['nome' => 'São Sebastião do Anta', 'estado_id' => 13],
            ['nome' => 'São Sebastião do Maranhão', 'estado_id' => 13],
            ['nome' => 'São Sebastião do Oeste', 'estado_id' => 13],
            ['nome' => 'São Sebastião do Paraíso', 'estado_id' => 13],
            ['nome' => 'São Sebastião do Rio Preto', 'estado_id' => 13],
            ['nome' => 'São Sebastião do Rio Verde', 'estado_id' => 13],
            ['nome' => 'São Thomé das Letras', 'estado_id' => 13],
            ['nome' => 'São Tiago', 'estado_id' => 13],
            ['nome' => 'São Tomás de Aquino', 'estado_id' => 13],
            ['nome' => 'São Vicente de Minas', 'estado_id' => 13],
            ['nome' => 'Sapucaí-Mirim', 'estado_id' => 13],
            ['nome' => 'Sardoá', 'estado_id' => 13],
            ['nome' => 'Sarzedo', 'estado_id' => 13],
            ['nome' => 'Sem-Peixe', 'estado_id' => 13],
            ['nome' => 'Senador Amaral', 'estado_id' => 13],
            ['nome' => 'Senador Cortes', 'estado_id' => 13],
            ['nome' => 'Senador Firmino', 'estado_id' => 13],
            ['nome' => 'Senador José Bento', 'estado_id' => 13],
            ['nome' => 'Senador Modestino Gonçalves', 'estado_id' => 13],
            ['nome' => 'Senhora de Oliveira', 'estado_id' => 13],
            ['nome' => 'Senhora do Porto', 'estado_id' => 13],
            ['nome' => 'Senhora dos Remédios', 'estado_id' => 13],
            ['nome' => 'Sericita', 'estado_id' => 13],
            ['nome' => 'Seritinga', 'estado_id' => 13],
            ['nome' => 'Serra Azul de Minas', 'estado_id' => 13],
            ['nome' => 'Serra da Saudade', 'estado_id' => 13],
            ['nome' => 'Serra do Salitre', 'estado_id' => 13],
            ['nome' => 'Serra dos Aimorés', 'estado_id' => 13],
            ['nome' => 'Serrania', 'estado_id' => 13],
            ['nome' => 'Serranópolis de Minas', 'estado_id' => 13],
            ['nome' => 'Serranos', 'estado_id' => 13],
            ['nome' => 'Serro', 'estado_id' => 13],
            ['nome' => 'Sete Lagoas', 'estado_id' => 13],
            ['nome' => 'Setubinha', 'estado_id' => 13],
            ['nome' => 'Silveirânia', 'estado_id' => 13],
            ['nome' => 'Silvianópolis', 'estado_id' => 13],
            ['nome' => 'Simão Pereira', 'estado_id' => 13],
            ['nome' => 'Simonésia', 'estado_id' => 13],
            ['nome' => 'Sobrália', 'estado_id' => 13],
            ['nome' => 'Soledade de Minas', 'estado_id' => 13],
            ['nome' => 'Tabuleiro', 'estado_id' => 13],
            ['nome' => 'Taiobeiras', 'estado_id' => 13],
            ['nome' => 'Taparuba', 'estado_id' => 13],
            ['nome' => 'Tapira', 'estado_id' => 13],
            ['nome' => 'Tapiraí', 'estado_id' => 13],
            ['nome' => 'Taquaraçu de Minas', 'estado_id' => 13],
            ['nome' => 'Tarumirim', 'estado_id' => 13],
            ['nome' => 'Teixeiras', 'estado_id' => 13],
            ['nome' => 'Teófilo Otoni', 'estado_id' => 13],
            ['nome' => 'Timóteo', 'estado_id' => 13],
            ['nome' => 'Tiradentes', 'estado_id' => 13],
            ['nome' => 'Tiros', 'estado_id' => 13],
            ['nome' => 'Tocantins', 'estado_id' => 13],
            ['nome' => 'Tocos do Moji', 'estado_id' => 13],
            ['nome' => 'Toledo', 'estado_id' => 13],
            ['nome' => 'Tombos', 'estado_id' => 13],
            ['nome' => 'Três Corações', 'estado_id' => 13],
            ['nome' => 'Três Marias', 'estado_id' => 13],
            ['nome' => 'Três Pontas', 'estado_id' => 13],
            ['nome' => 'Tumiritinga', 'estado_id' => 13],
            ['nome' => 'Tupaciguara', 'estado_id' => 13],
            ['nome' => 'Turmalina', 'estado_id' => 13],
            ['nome' => 'Turvolândia', 'estado_id' => 13],
            ['nome' => 'Ubá', 'estado_id' => 13],
            ['nome' => 'Ubaí', 'estado_id' => 13],
            ['nome' => 'Ubaporanga', 'estado_id' => 13],
            ['nome' => 'Uberaba', 'estado_id' => 13],
            ['nome' => 'Uberlândia', 'estado_id' => 13],
            ['nome' => 'Umburatiba', 'estado_id' => 13],
            ['nome' => 'Unaí', 'estado_id' => 13],
            ['nome' => 'União de Minas', 'estado_id' => 13],
            ['nome' => 'Uruana de Minas', 'estado_id' => 13],
            ['nome' => 'Urucânia', 'estado_id' => 13],
            ['nome' => 'Urucuia', 'estado_id' => 13],
            ['nome' => 'Vargem Alegre', 'estado_id' => 13],
            ['nome' => 'Vargem Bonita', 'estado_id' => 13],
            ['nome' => 'Vargem Grande do Rio Pardo', 'estado_id' => 13],
            ['nome' => 'Varginha', 'estado_id' => 13],
            ['nome' => 'Varjão de Minas', 'estado_id' => 13],
            ['nome' => 'Várzea da Palma', 'estado_id' => 13],
            ['nome' => 'Varzelândia', 'estado_id' => 13],
            ['nome' => 'Vazante', 'estado_id' => 13],
            ['nome' => 'Verdelândia', 'estado_id' => 13],
            ['nome' => 'Veredinha', 'estado_id' => 13],
            ['nome' => 'Veríssimo', 'estado_id' => 13],
            ['nome' => 'Vermelho Novo', 'estado_id' => 13],
            ['nome' => 'Vespasiano', 'estado_id' => 13],
            ['nome' => 'Viçosa', 'estado_id' => 13],
            ['nome' => 'Vieiras', 'estado_id' => 13],
            ['nome' => 'Virgem da Lapa', 'estado_id' => 13],
            ['nome' => 'Virgínia', 'estado_id' => 13],
            ['nome' => 'Virginópolis', 'estado_id' => 13],
            ['nome' => 'Virgolândia', 'estado_id' => 13],
            ['nome' => 'Visconde do Rio Branco', 'estado_id' => 13],
            ['nome' => 'Volta Grande', 'estado_id' => 13],
            ['nome' => 'Wenceslau Braz', 'estado_id' => 13]
        ]);

        $this->command->info('Cidades de Minas Gerais importadas com sucesso!');
    }
}