<?php

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;

class CidadesPernambucoSeeder extends Seeder {

    /**
    * Run the database seeds.
    *
    * @return void
    */
    public function run()
    {
        DB::table('cidades')->insert([
        	['nome' => 'Abreu e Lima', 'estado_id' => 17],
            ['nome' => 'Afogados da Ingazeira', 'estado_id' => 17],
            ['nome' => 'Afrânio', 'estado_id' => 17],
            ['nome' => 'Agrestina', 'estado_id' => 17],
            ['nome' => 'Água Preta', 'estado_id' => 17],
            ['nome' => 'Águas Belas', 'estado_id' => 17],
            ['nome' => 'Alagoinha', 'estado_id' => 17],
            ['nome' => 'Aliança', 'estado_id' => 17],
            ['nome' => 'Altinho', 'estado_id' => 17],
            ['nome' => 'Amaraji', 'estado_id' => 17],
            ['nome' => 'Angelim', 'estado_id' => 17],
            ['nome' => 'Araçoiaba', 'estado_id' => 17],
            ['nome' => 'Araripina', 'estado_id' => 17],
            ['nome' => 'Arcoverde', 'estado_id' => 17],
            ['nome' => 'Barra de Guabiraba', 'estado_id' => 17],
            ['nome' => 'Barreiros', 'estado_id' => 17],
            ['nome' => 'Belém de Maria', 'estado_id' => 17],
            ['nome' => 'Belém de São Francisco', 'estado_id' => 17],
            ['nome' => 'Belo Jardim', 'estado_id' => 17],
            ['nome' => 'Betânia', 'estado_id' => 17],
            ['nome' => 'Bezerros', 'estado_id' => 17],
            ['nome' => 'Bodocó', 'estado_id' => 17],
            ['nome' => 'Bom Conselho', 'estado_id' => 17],
            ['nome' => 'Bom Jardim', 'estado_id' => 17],
            ['nome' => 'Bonito', 'estado_id' => 17],
            ['nome' => 'Brejão', 'estado_id' => 17],
            ['nome' => 'Brejinho', 'estado_id' => 17],
            ['nome' => 'Brejo da Madre de Deus', 'estado_id' => 17],
            ['nome' => 'Buenos Aires', 'estado_id' => 17],
            ['nome' => 'Buíque', 'estado_id' => 17],
            ['nome' => 'Cabo de Santo Agostinho', 'estado_id' => 17],
            ['nome' => 'Cabrobó', 'estado_id' => 17],
            ['nome' => 'Cachoeirinha', 'estado_id' => 17],
            ['nome' => 'Caetés', 'estado_id' => 17],
            ['nome' => 'Calçado', 'estado_id' => 17],
            ['nome' => 'Calumbi', 'estado_id' => 17],
            ['nome' => 'Camaragibe', 'estado_id' => 17],
            ['nome' => 'Camocim de São Félix', 'estado_id' => 17],
            ['nome' => 'Camutanga', 'estado_id' => 17],
            ['nome' => 'Canhotinho', 'estado_id' => 17],
            ['nome' => 'Capoeiras', 'estado_id' => 17],
            ['nome' => 'Carnaíba', 'estado_id' => 17],
            ['nome' => 'Carnaubeira da Penha', 'estado_id' => 17],
            ['nome' => 'Carpina', 'estado_id' => 17],
            ['nome' => 'Caruaru', 'estado_id' => 17],
            ['nome' => 'Casinhas', 'estado_id' => 17],
            ['nome' => 'Catende', 'estado_id' => 17],
            ['nome' => 'Cedro', 'estado_id' => 17],
            ['nome' => 'Chã de Alegria', 'estado_id' => 17],
            ['nome' => 'Chã Grande', 'estado_id' => 17],
            ['nome' => 'Condado', 'estado_id' => 17],
            ['nome' => 'Correntes', 'estado_id' => 17],
            ['nome' => 'Cortês', 'estado_id' => 17],
            ['nome' => 'Cumaru', 'estado_id' => 17],
            ['nome' => 'Cupira', 'estado_id' => 17],
            ['nome' => 'Custódia', 'estado_id' => 17],
            ['nome' => 'Dormentes', 'estado_id' => 17],
            ['nome' => 'Escada', 'estado_id' => 17],
            ['nome' => 'Exu', 'estado_id' => 17],
            ['nome' => 'Feira Nova', 'estado_id' => 17],
            ['nome' => 'Fernando de Noronha', 'estado_id' => 17],
            ['nome' => 'Ferreiros', 'estado_id' => 17],
            ['nome' => 'Flores', 'estado_id' => 17],
            ['nome' => 'Floresta', 'estado_id' => 17],
            ['nome' => 'Frei Miguelinho', 'estado_id' => 17],
            ['nome' => 'Gameleira', 'estado_id' => 17],
            ['nome' => 'Garanhuns', 'estado_id' => 17],
            ['nome' => 'Glória do Goitá', 'estado_id' => 17],
            ['nome' => 'Goiana', 'estado_id' => 17],
            ['nome' => 'Granito', 'estado_id' => 17],
            ['nome' => 'Gravatá', 'estado_id' => 17],
            ['nome' => 'Iati', 'estado_id' => 17],
            ['nome' => 'Ibimirim', 'estado_id' => 17],
            ['nome' => 'Ibirajuba', 'estado_id' => 17],
            ['nome' => 'Igarassu', 'estado_id' => 17],
            ['nome' => 'Iguaraci', 'estado_id' => 17],
            ['nome' => 'Ilha de Itamaracá', 'estado_id' => 17],
            ['nome' => 'Inajá', 'estado_id' => 17],
            ['nome' => 'Ingazeira', 'estado_id' => 17],
            ['nome' => 'Ipojuca', 'estado_id' => 17],
            ['nome' => 'Ipubi', 'estado_id' => 17],
            ['nome' => 'Itacuruba', 'estado_id' => 17],
            ['nome' => 'Itaíba', 'estado_id' => 17],
            ['nome' => 'Itambé', 'estado_id' => 17],
            ['nome' => 'Itapetim', 'estado_id' => 17],
            ['nome' => 'Itapissuma', 'estado_id' => 17],
            ['nome' => 'Itaquitinga', 'estado_id' => 17],
            ['nome' => 'Jaboatão dos Guararapes', 'estado_id' => 17],
            ['nome' => 'Jaqueira', 'estado_id' => 17],
            ['nome' => 'Jataúba', 'estado_id' => 17],
            ['nome' => 'Jatobá', 'estado_id' => 17],
            ['nome' => 'João Alfredo', 'estado_id' => 17],
            ['nome' => 'Joaquim Nabuco', 'estado_id' => 17],
            ['nome' => 'Jucati', 'estado_id' => 17],
            ['nome' => 'Jupi', 'estado_id' => 17],
            ['nome' => 'Jurema', 'estado_id' => 17],
            ['nome' => 'Lagoa do Carro', 'estado_id' => 17],
            ['nome' => 'Lagoa do Itaenga', 'estado_id' => 17],
            ['nome' => 'Lagoa do Ouro', 'estado_id' => 17],
            ['nome' => 'Lagoa dos Gatos', 'estado_id' => 17],
            ['nome' => 'Lagoa Grande', 'estado_id' => 17],
            ['nome' => 'Lajedo', 'estado_id' => 17],
            ['nome' => 'Limoeiro', 'estado_id' => 17],
            ['nome' => 'Macaparana', 'estado_id' => 17],
            ['nome' => 'Machados', 'estado_id' => 17],
            ['nome' => 'Manari', 'estado_id' => 17],
            ['nome' => 'Maraial', 'estado_id' => 17],
            ['nome' => 'Mirandiba', 'estado_id' => 17],
            ['nome' => 'Moreilândia', 'estado_id' => 17],
            ['nome' => 'Moreno', 'estado_id' => 17],
            ['nome' => 'Nazaré da Mata', 'estado_id' => 17],
            ['nome' => 'Olinda', 'estado_id' => 17],
            ['nome' => 'Orobó', 'estado_id' => 17],
            ['nome' => 'Orocó', 'estado_id' => 17],
            ['nome' => 'Ouricuri', 'estado_id' => 17],
            ['nome' => 'Palmares', 'estado_id' => 17],
            ['nome' => 'Palmeirina', 'estado_id' => 17],
            ['nome' => 'Panelas', 'estado_id' => 17],
            ['nome' => 'Paranatama', 'estado_id' => 17],
            ['nome' => 'Parnamirim', 'estado_id' => 17],
            ['nome' => 'Passira', 'estado_id' => 17],
            ['nome' => 'Paudalho', 'estado_id' => 17],
            ['nome' => 'Paulista', 'estado_id' => 17],
            ['nome' => 'Pedra', 'estado_id' => 17],
            ['nome' => 'Pesqueira', 'estado_id' => 17],
            ['nome' => 'Petrolândia', 'estado_id' => 17],
            ['nome' => 'Petrolina', 'estado_id' => 17],
            ['nome' => 'Poção', 'estado_id' => 17],
            ['nome' => 'Pombos', 'estado_id' => 17],
            ['nome' => 'Primavera', 'estado_id' => 17],
            ['nome' => 'Quipapá', 'estado_id' => 17],
            ['nome' => 'Quixaba', 'estado_id' => 17],
            ['nome' => 'Recife', 'estado_id' => 17],
            ['nome' => 'Riacho das Almas', 'estado_id' => 17],
            ['nome' => 'Ribeirão', 'estado_id' => 17],
            ['nome' => 'Rio Formoso', 'estado_id' => 17],
            ['nome' => 'Sairé', 'estado_id' => 17],
            ['nome' => 'Salgadinho', 'estado_id' => 17],
            ['nome' => 'Salgueiro', 'estado_id' => 17],
            ['nome' => 'Saloá', 'estado_id' => 17],
            ['nome' => 'Sanharó', 'estado_id' => 17],
            ['nome' => 'Santa Cruz', 'estado_id' => 17],
            ['nome' => 'Santa Cruz da Baixa Verde', 'estado_id' => 17],
            ['nome' => 'Santa Cruz do Capibaribe', 'estado_id' => 17],
            ['nome' => 'Santa Filomena', 'estado_id' => 17],
            ['nome' => 'Santa Maria da Boa Vista', 'estado_id' => 17],
            ['nome' => 'Santa Maria do Cambucá', 'estado_id' => 17],
            ['nome' => 'Santa Terezinha', 'estado_id' => 17],
            ['nome' => 'São Benedito do Sul', 'estado_id' => 17],
            ['nome' => 'São Bento do Una', 'estado_id' => 17],
            ['nome' => 'São Caitano', 'estado_id' => 17],
            ['nome' => 'São João', 'estado_id' => 17],
            ['nome' => 'São Joaquim do Monte', 'estado_id' => 17],
            ['nome' => 'São José da Coroa Grande', 'estado_id' => 17],
            ['nome' => 'São José do Belmonte', 'estado_id' => 17],
            ['nome' => 'São José do Egito', 'estado_id' => 17],
            ['nome' => 'São Lourenço da Mata', 'estado_id' => 17],
            ['nome' => 'São Vicente Ferrer', 'estado_id' => 17],
            ['nome' => 'Serra Talhada', 'estado_id' => 17],
            ['nome' => 'Serrita', 'estado_id' => 17],
            ['nome' => 'Sertânia', 'estado_id' => 17],
            ['nome' => 'Sirinhaém', 'estado_id' => 17],
            ['nome' => 'Solidão', 'estado_id' => 17],
            ['nome' => 'Surubim', 'estado_id' => 17],
            ['nome' => 'Tabira', 'estado_id' => 17],
            ['nome' => 'Tacaimbó', 'estado_id' => 17],
            ['nome' => 'Tacaratu', 'estado_id' => 17],
            ['nome' => 'Tamandaré', 'estado_id' => 17],
            ['nome' => 'Taquaritinga do Norte', 'estado_id' => 17],
            ['nome' => 'Terezinha', 'estado_id' => 17],
            ['nome' => 'Terra Nova', 'estado_id' => 17],
            ['nome' => 'Timbaúba', 'estado_id' => 17],
            ['nome' => 'Toritama', 'estado_id' => 17],
            ['nome' => 'Tracunhaém', 'estado_id' => 17],
            ['nome' => 'Trindade', 'estado_id' => 17],
            ['nome' => 'Triunfo', 'estado_id' => 17],
            ['nome' => 'Tupanatinga', 'estado_id' => 17],
            ['nome' => 'Tuparetama', 'estado_id' => 17],
            ['nome' => 'Venturosa', 'estado_id' => 17],
            ['nome' => 'Verdejante', 'estado_id' => 17],
            ['nome' => 'Vertente do Lério', 'estado_id' => 17],
            ['nome' => 'Vertentes', 'estado_id' => 17],
            ['nome' => 'Vicência', 'estado_id' => 17],
            ['nome' => 'Vitória de Santo Antão', 'estado_id' => 17],
            ['nome' => 'Xexéu', 'estado_id' => 17]
        ]);

        $this->command->info('Cidades do Pernambuco importadas com sucesso!');
    }
}
